#! /bin/sh
TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi

MAKE="make MODE=debug -j4"

opp_test gen -v *.test || exit 1

(
	cd mocks;
	opp_makemake --make-so -o smile_mocks -f --deep -KINET_PROJ=../../../inet -DINET_IMPORT -I. \
	             -I$\(INET_PROJ\)/src -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out//$\(CONFIGNAME\)/src \
	             -lINET_dbg -lsmile_dbg;
	$MAKE
) || exit 1

(
	cd work;
	opp_makemake -f --deep -KINET_PROJ=../../../inet -DINET_IMPORT -I. -I$\(INET_PROJ\)/src \
	             -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out//$\(CONFIGNAME\)/src -lINET_dbg \
	             -L../mocks -lsmile_dbg -lsmile_mocks_dbg;
    $MAKE
) || exit 1

export NEDPATH=.:`pwd`/../src:`pwd`/../../inet/src:`pwd`/mocks
opp_test run -v -p smile_dbg $TESTFILES