#! /bin/sh

set -e

print_help()
{
    echo "One of mandatory paths is missing."
    echo ""
    echo "Usage:"
    echo "    ./runtest INET_PATH"
}

if [ "x$1" = "x" ]; then
    print_help
    exit 1
fi

TESTFILES='*.test'

if [ ! -d work ]; then
    mkdir work
fi

MAKE="make MODE=debug -j $(nproc) V=1"

opp_test gen -v *.test || exit 1

(
	cd mocks;
	opp_makemake --make-so -o smile_mocks -f --deep -KINET_PROJ=../$1 -DINET_IMPORT -I. \
	             -I$\(INET_PROJ\)/src -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out/$\(CONFIGNAME\)/src \
	             -I../../src -lINET_dbg -lsmile_dbg -lstdc++fs;
	$MAKE
) || exit 1

(
	cd fakes;
	opp_makemake --make-so -o smile_fakes -f --deep -KINET_PROJ=../$1 -DINET_IMPORT -I. \
	             -I$\(INET_PROJ\)/src -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out//$\(CONFIGNAME\)/src \
	             -I../../src -lINET_dbg -lsmile_dbg -lstdc++fs;
	$MAKE
) || exit 1

(
	cd testers;
	opp_makemake --make-so -o smile_testers -f --deep -KINET_PROJ=../$1 -DINET_IMPORT -I. \
	             -I$\(INET_PROJ\)/src -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out//$\(CONFIGNAME\)/src \
	             -I../../src -lINET_dbg -lsmile_dbg -lstdc++fs;
	$MAKE
) || exit 1

(
	cd work;
	opp_makemake -f --deep -KINET_PROJ=../$1 -DINET_IMPORT -I. -I$\(INET_PROJ\)/src \
	             -L$\(INET_PROJ\)/out/$\(CONFIGNAME\)/src -L../../out//$\(CONFIGNAME\)/src -lINET_dbg \
	             -L../mocks -L../fakes -L../testers -lsmile_dbg -lsmile_mocks_dbg -lsmile_fakes_dbg -lsmile_testers_dbg -lstdc++fs;
    $MAKE
) || exit 1

export NEDPATH=.:`pwd`/../src:`pwd`/../src/steinhauser_clock:`pwd`/$1/src:`pwd`/mocks:`pwd`/fakes:`pwd`/testers
opp_test run -v -p smile_dbg $TESTFILES
